name: Auto Update node1 on Machine

on:
  push:
    branches:
      - main

jobs:
  update-node1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4



      - name: SSH into machine and update node1
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} "cd /home/netstratum/Docker/loadbalance/site && git pull origin main"
