name: Update files on push
on: [push]
jobs:
  update-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Modify the specific files
      uses: jaywcjlove/github-action-modify-file-content@main
      with:
        path: /home/netstratum/Docker/loadbalance/site/node1
        body: "Your new content"
        overwrite: 'true'
    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add -A
        git commit -m "Update file on push"
        git push
