name: Auto Update node1 on Machine

on:
  push:
    branches:
      - main

jobs:
  update-node1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4



      - name: SSH into machine and update node1
        run: |
          ssh -o StrictHostKeyChecking=no -p 8022 ananthan@${{ secrets.SERVER_IP }} "cd /home/ananthan/docker/site/ && git pull origin main"

