name: Update resources
on: [push]
jobs:
  resources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Update resources
      uses: test-room-7/action-update-file@v1
      with:
        file-path: /home/netstratum/Docker/loadbalance/site/node1
        commit-msg: "Update file on push"
        github-token: ${{ secrets.GITHUB_TOKEN }}
